version: '3.5'
services:
  twitch-watcher:
    build: . #For local build
    image: twitch-watcher #For local build
    #image: frosty5689/twitch-watcher:latest #For Docker Hub image
    restart: always
    environment:
      - token=rxk38rh5qtyw95fkvm7kgfceh4mh6u #Example value from readme
      - streamersUrl=https://www.twitch.tv/directory/game/Warframe?tl=c2542d6d-cd10-4532-919b-3d19f30a768b
      #- streamersUrl=https://www.twitch.tv/directory/game/Rocket%20League?tl=c2542d6d-cd10-4532-919b-3d19f30a768b
      #- streamersUrl=https://www.twitch.tv/kellphy/videos
      #- watchAlwaysTopStreamer=true
      #- channelsWithPriority=kellphy
      #- userAgent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
      #- scrollDelay=2000
      #- scrollTimes=5
      #- minWatching=5
      #- maxWatching=10
      #- noChannelFoundWait=5
      #- checkForDrops=true
      #- browserClean=1
      #- browserCleanUnit=hour
      #- browserScreenshot=false
      #- proxy=ip:port
      #- proxyAuth=username:password
    #volumes:
    #  - "./screenshots:/usr/src/app/screenshots"
